services:
  flood:
    image: jesec/flood
    user: 1000:1001
    restart: unless-stopped
    command: --port 3001 --allowedpath /data
    environment:
      HOME: /config
    volumes:
      - /Users/balli/config:/config
      - /Users/balli/Downloads:/data
    ports:
      - 3001:3001

  rtorrent:
    image: jesec/rtorrent
    user: 1000:1001
    restart: unless-stopped
    command: -o network.port_range.set=6881-6881,system.daemon.set=true
    environment:
      HOME: /config
    volumes:
      - /Users/balli/config:/config
      - /Users/balli/Downloads:/data
    ports:
      - 6881:6881
